### ISSUE TITLE
WebConfig cannot connect to the device.

### ISSUE THREAD

**Issue by RinChanNOWWW** [mon/PocketVoltex#1]
It worked in the past, but it don't work now. How can I figure out the problem?

When I use webconfig online:

```
Opening device...
NetworkError: Unable to claim interface.
Device disconnected.
```

When I use webconfig html on my own computer:

```
Opening device...
NotFoundError: The device was disconnected.
```

**Comment by mon** [comment]
Try the Zadig fix detailed here:
https://github.com/mon/PocketVoltex/blob/master/Docs/Configuration.md#networkerror-unable-to-claim-interface

**Comment by RinChanNOWWW** [comment]
> Try the Zadig fix detailed here:
> [`master`/Docs/Configuration.md#networkerror-unable-to-claim-interface](https://github.com/mon/PocketVoltex/blob/master/Docs/Configuration.md#networkerror-unable-to-claim-interface)

Thanks! It works.
