### ISSUE TITLE
PocketVoltex with ProMicro

### ISSUE THREAD

**Issue by L4Ph** [mon/PocketVoltex#2]
This keyboard is very practical (especially in Japan, where there is a definite demand for it), and since there is an actual store in Japan related to homemade keyboards called Yusha Kobo, we'd really like to see it supported!

**Comment by mon** [comment]
I've been to that store! Such a wonderful place.

I'm a little confused as to the request, though. What are you proposing?
- Pocket Voltex with socket/connectors for Pro Micro
- Pocket Voltex that supports using the Arduino Bootloader (atmega32u4 and correct pinout)

I am currently designing a new version that uses the 32u2 (note: u2 not u4, less pins) which can use an arduino core I think, I haven't checked. It will also have a plastic case, so it's taking a bit of time.

I think, for a more DIY friendly Pocket Voltex you might want to look at https://github.com/speedypotato/Pocket-SDVX
It uses a Pro Micro already! And uses a 3D printed case. It's very maker-friendly ^_^
