### ISSUE TITLE
about fireware

### ISSUE THREAD

**Issue by HHHHHWTF** [mon/PocketVoltex#4]
When I download LUFA170418 and copy LUFA file folder and run a .bat file name multiflasher from PocketVoltex on Firmware,I get some code:
      0 [main] sh 10300 sync_with_child: child 18804(0x1E0) died before initialization with status code 0xC0000142
    158 [main] sh 10300 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 9252 sync_with_child: child 1840(0x1EC) died before initialization with status code 0xC0000142
    119 [main] sh 9252 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 19276 sync_with_child: child 14104(0x1EC) died before initialization with status code 0xC0000142
    223 [main] sh 19276 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
 [GCC]     : Compiling C file "PocketVoltex.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/ -Werror  -I. -I../LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_USER -DF_USB=16000000UL  -MMD -MP -MF obj/PocketVoltex.d PocketVoltex.c -o obj/PocketVoltex.o
Assembler messages:
Fatal error: can't create obj/PocketVoltex.o: No such file or directory
How can I deal with this problem?

**Comment by mon** [comment]
I know you closed this issue, but I just uploaded EVERY manufacturing file:
https://github.com/mon/PocketVoltex/releases/tag/rev7

Good luck! Please email me if you have success.
